In [5]:
import numpy as np

np.__version__         # version

'1.20.3'

In [2]:
a = [1,3,4,5]          # 1d array
np.array(a)

array([1, 3, 4, 5])

In [37]:
np.ndim(a)

1

In [45]:
np.array(a).shape

(4,)

In [239]:
np.array(a).size       # len(np.array(a))

4

In [240]:
np.array(a).dtype

dtype('int64')

In [56]:
np.array(a)[3]

5

In [57]:
np.array(a)[[3]]

array([5])

In [6]:
b = [[1,2,3,4], [5, 6, 7, 8]]      # 2d
array2 = np.array(b)
array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [59]:
array2.shape

(2, 4)

In [51]:
array2.dtype

dtype('int64')

In [241]:
array2[0][1]       # single num

2

In [242]:
array2[0,1]        # alternative way to express

2

In [530]:
array2[[0],[1]]    # array

array([2])

In [243]:
array2[:,2]        # second col

array([3, 7])

In [244]:
array2[-2,:2]      # last 2 row(1st row in here) and first 2 cols

array([1, 2])

In [471]:
array2[[0,1],1:] # multi-slice  

array([[2, 3, 4],
       [6, 7, 8]])

In [60]:
c = np.zeros(10)   # default datatype is float
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [75]:
c.dtype = np.int64               # convert type
c = c.astype(np.int32)           # same logical
c

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [212]:
d = np.empty((2,3),dtype = bool)
d

array([[ True,  True,  True],
       [ True,  True,  True]])

In [78]:
e = np.ones((2, 3, 2)) # 3d
e

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [246]:
e = np.full((2,3),6)  # arbitrary num
e

array([[6, 6, 6],
       [6, 6, 6]])

In [249]:
e = np.full_like(b, -99)   # inherit the dtype and the ndim of array b but subsititude a arbitrary num
e                          # alternative:       np.full(b.shape,-99)

array([[-99, -99, -99, -99],
       [-99, -99, -99, -99]])

In [32]:
np.linspace(0,2, num = 9, endpoint = True)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [7]:
arr1 = np.arange(6)
arr1

array([0, 1, 2, 3, 4, 5])

In [85]:
arr2 = np.random.randn(1,3,2)                  # normal distribution but cannot define m and sd
arr2

array([[[ 0.5296957 ,  0.90771667],
        [ 0.44748629,  0.22874433],
        [-0.32814106,  0.14686456]]])

In [23]:
arr3 = np.random.rand(6, 3)                    # uniform distri witin 0 to 1
arr3

array([[0.06648696, 0.69015891, 0.90350701],
       [0.58118545, 0.81752524, 0.4153491 ],
       [0.56064353, 0.42937836, 0.26237735],
       [0.84619948, 0.19940264, 0.95019807],
       [0.64087526, 0.71570292, 0.13678163],
       [0.95886054, 0.95033487, 0.68579825]])

In [389]:
np.random.randint(1, 10, size = (2,3))

array([[6, 7, 8],
       [3, 4, 9]])

In [183]:
arr3[arr1>3]         # onlt last two 1d array counts

array([[0.71986483, 0.64165925, 0.4196345 ],
       [0.13376489, 0.34478459, 0.51020815]])

In [186]:
arr3[~(arr1<3),1:]   # last 3 and index 1 to end

array([[0.44788238, 0.55397311],
       [0.64165925, 0.4196345 ],
       [0.34478459, 0.51020815]])

In [187]:
arr3[~(arr1<3)][1:]  # consider arr3[~(arr1<3)] then [1:] 

array([[0.71986483, 0.64165925, 0.4196345 ],
       [0.13376489, 0.34478459, 0.51020815]])

In [229]:
arr3[0,2] == arr3[0][2] # kind of tricky

True

In [230]:
arr3[[0,2]]           # row 0 and row 2

array([[0.78524274, 0.79315215, 0.74034795],
       [0.85044563, 0.31156476, 0.66496629]])

In [232]:
arr3[[0],[2]]        

array([0.74034795])

In [234]:
arr3[:5,1:]

array([[0.79315215, 0.74034795],
       [0.72569087, 0.74902172],
       [0.31156476, 0.66496629],
       [0.44788238, 0.55397311],
       [0.64165925, 0.4196345 ]])

###### reshape the array


In [193]:
arr4 = arr1.reshape(2,3)   # reshape to 2d
arr4

array([[0, 1, 2],
       [3, 4, 5]])

In [194]:
arr4[[0,1],[1,2]]     # extract arr4[0,1] and arr4[1,2]

array([1, 5])

In [198]:
arr4 = arr1.reshape((2,3,1))  # reshape to 3d
arr4

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [202]:
arr3.T    # 6,3 -> 3,6

array([[0.78524274, 0.0499921 , 0.85044563, 0.46849453, 0.71986483,
        0.13376489],
       [0.79315215, 0.72569087, 0.31156476, 0.44788238, 0.64165925,
        0.34478459],
       [0.74034795, 0.74902172, 0.66496629, 0.55397311, 0.4196345 ,
        0.51020815]])

In [203]:
arr2.T     # 1,3,2 -> 2,3,1

array([[[ 0.5296957 ],
        [ 0.44748629],
        [-0.32814106]],

       [[ 0.90771667],
        [ 0.22874433],
        [ 0.14686456]]])

In [474]:
np.split(arr3,3)   # recall that split into list

[array([[0.01451087, 0.02931286, 0.71764568],
        [0.37320018, 0.37884991, 0.02533558]]),
 array([[0.03669962, 0.29188217, 0.33886243],
        [0.12440897, 0.10642023, 0.92552646]]),
 array([[0.45719617, 0.22177923, 0.24981276],
        [0.67214306, 0.61795397, 0.55988029]])]

In [10]:
print(arr1[:,np.newaxis], arr1[None,:], sep = '\n\n')    # just for curious

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]

[[0 1 2 3 4 5]]


# array stack/unstack(concatenate and split also insert and delete) and repeat/tile


In [207]:
np.array(list(zip(arr1, np.array([1,2,3,5]))))     # stack 1d array to 2d array

array([[0, 1],
       [1, 2],
       [2, 3],
       [3, 5]])

In [463]:
np.stack((arr1,np.array([1,2,6,8,13,15])),axis=1)  # same effect(axis=0 is row, 1 is col)

array([[ 0,  1],
       [10,  2],
       [ 2,  6],
       [ 3,  8],
       [ 4, 13],
       [ 5, 15]])

In [459]:
np.vstack((arr1,np.array([1,2,6,8,13,15])))

array([[ 0, 10,  2,  3,  4,  5],
       [ 1,  2,  6,  8, 13, 15]])

In [460]:
np.hstack((arr1,np.array([1,2,6,8,13,15])))

array([ 0, 10,  2,  3,  4,  5,  1,  2,  6,  8, 13, 15])

In [11]:
np.dstack((arr1,np.array([1,2,6,8,13,15])))        # stack 1d array to 3d array

array([[[ 0,  1],
        [ 1,  2],
        [ 2,  6],
        [ 3,  8],
        [ 4, 13],
        [ 5, 15]]])

In [17]:
txt = "hello, my name is Peter, I am 26 years old"
txt.split(", ")

['hello', 'my name is Peter', 'I am 26 years old']

In [12]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [13]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
upper, lower = np.vsplit(grid, [2])
print(upper, lower, sep = '\n\n')

[[0 1 2 3]
 [4 5 6 7]]

[[ 8  9 10 11]
 [12 13 14 15]]


In [15]:
left, right = np.hsplit(grid, [2])
print(left,right,sep='\n\n')

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [21]:
print(np.concatenate([np.ones((6,1)),np.zeros((6,1))],axis=0),
     np.concatenate([np.ones((6,1)),np.zeros((6,1))],axis=1), sep='\n\n')   # 2d array or higher could apply axis=1

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]


In [19]:
np.concatenate([np.ones(6),np.zeros(6)],axis=0)   # recall that 1d array only has one axis = 0

array([1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.])

In [25]:
print(arr3, np.delete(arr3,2,axis=1), np.delete(arr3,2,axis=0), sep = '\n\n')                 # delete col 2 and row 2

[[0.06648696 0.69015891 0.90350701]
 [0.58118545 0.81752524 0.4153491 ]
 [0.56064353 0.42937836 0.26237735]
 [0.84619948 0.19940264 0.95019807]
 [0.64087526 0.71570292 0.13678163]
 [0.95886054 0.95033487 0.68579825]]

[[0.06648696 0.69015891]
 [0.58118545 0.81752524]
 [0.56064353 0.42937836]
 [0.84619948 0.19940264]
 [0.64087526 0.71570292]
 [0.95886054 0.95033487]]

[[0.06648696 0.69015891 0.90350701]
 [0.58118545 0.81752524 0.4153491 ]
 [0.84619948 0.19940264 0.95019807]
 [0.64087526 0.71570292 0.13678163]
 [0.95886054 0.95033487 0.68579825]]


In [493]:
np.insert(arr3,3,arr1[:3],axis=0) 

array([[ 0.01451087,  0.02931286,  0.71764568],
       [ 0.37320018,  0.37884991,  0.02533558],
       [ 0.03669962,  0.29188217,  0.33886243],
       [ 0.        , 10.        ,  2.        ],
       [ 0.12440897,  0.10642023,  0.92552646],
       [ 0.45719617,  0.22177923,  0.24981276],
       [ 0.67214306,  0.61795397,  0.55988029]])

In [27]:
print(arr3)
print()
print(np.repeat(arr3,2, axis = 1))
print()
print(np.repeat(arr3,2, axis = 0))

[[0.06648696 0.69015891 0.90350701]
 [0.58118545 0.81752524 0.4153491 ]
 [0.56064353 0.42937836 0.26237735]
 [0.84619948 0.19940264 0.95019807]
 [0.64087526 0.71570292 0.13678163]
 [0.95886054 0.95033487 0.68579825]]

[[0.06648696 0.06648696 0.69015891 0.69015891 0.90350701 0.90350701]
 [0.58118545 0.58118545 0.81752524 0.81752524 0.4153491  0.4153491 ]
 [0.56064353 0.56064353 0.42937836 0.42937836 0.26237735 0.26237735]
 [0.84619948 0.84619948 0.19940264 0.19940264 0.95019807 0.95019807]
 [0.64087526 0.64087526 0.71570292 0.71570292 0.13678163 0.13678163]
 [0.95886054 0.95886054 0.95033487 0.95033487 0.68579825 0.68579825]]

[[0.06648696 0.69015891 0.90350701]
 [0.06648696 0.69015891 0.90350701]
 [0.58118545 0.81752524 0.4153491 ]
 [0.58118545 0.81752524 0.4153491 ]
 [0.56064353 0.42937836 0.26237735]
 [0.56064353 0.42937836 0.26237735]
 [0.84619948 0.19940264 0.95019807]
 [0.84619948 0.19940264 0.95019807]
 [0.64087526 0.71570292 0.13678163]
 [0.64087526 0.71570292 0.13678163]
 [0.95

In [28]:
np.repeat(arr1,3, axis = 0)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [29]:
np.tile(arr1,2)

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

## arithmetic and stats

In [441]:
np.add(np.arange(6),np.random.rand(6))         # a+b

array([0.73545742, 1.62733456, 2.75500279, 3.62367065, 4.07221653,
       5.5047742 ])

In [442]:
np.subtract(np.arange(6),np.random.rand(6))    # a-b

array([-0.78652532,  0.98911879,  1.06436104,  2.40962858,  3.70306156,
        4.48169635])

In [34]:
print(np.exp(arr1), np.exp2(arr1), np.power(5,arr1), sep='\n\n')

[  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591 ]

[ 1.  2.  4.  8. 16. 32.]

[   1    5   25  125  625 3125]


In [38]:
print(np.log(arr1[1:]), np.log2(arr1[1:]), np.log10(arr1[1:]), 
      np.log10(arr1[1:] + 2) / np.log10(arr1[1:]+1), sep='\n\n')

[0.         0.69314718 1.09861229 1.38629436 1.60943791]

[0.         1.         1.5849625  2.         2.32192809]

[0.         0.30103    0.47712125 0.60205999 0.69897   ]

[1.5849625  1.26185951 1.16096405 1.11328275 1.08603313]


In [41]:
print(arr1 + 5, arr1 + arr1[:,np.newaxis], arr1 + np.ones((6,6)), sep='\n\n')   # recycling rule

[ 5  6  7  8  9 10]

[[ 0  1  2  3  4  5]
 [ 1  2  3  4  5  6]
 [ 2  3  4  5  6  7]
 [ 3  4  5  6  7  8]
 [ 4  5  6  7  8  9]
 [ 5  6  7  8  9 10]]

[[1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]]


In [454]:
print(arr3)
print()
print(np.min(arr3))
print()                                # min num across whole array
print(np.sum(arr3,axis=1))             # sum each row
print(f'\n{np.sum(arr3,axis=0)}')      # sum each col

[[0.01451087 0.02931286 0.71764568]
 [0.37320018 0.37884991 0.02533558]
 [0.03669962 0.29188217 0.33886243]
 [0.12440897 0.10642023 0.92552646]
 [0.45719617 0.22177923 0.24981276]
 [0.67214306 0.61795397 0.55988029]]

0.014510870023278222

[0.76146942 0.77738566 0.66744422 1.15635566 0.92878816 1.84997732]

[1.67815887 1.64619837 2.8170632 ]


In [513]:
rand1 = np.array(np.random.randint(1,10,(2,3)))
rand2 = np.array(np.random.randint(1,20,(2,3)))

print(rand1,rand2,sep='\n')
print(np.where(rand1 == rand2))

[[4 7 1]
 [1 2 5]]
[[11 14 13]
 [ 1 13 19]]
(array([1]), array([0]))


In [521]:
np.tile(rand1,2)

array([[4, 7, 1, 4, 7, 1],
       [1, 2, 5, 1, 2, 5]])

In [525]:
np.repeat(rand1,2,axis=1)

array([[4, 4, 7, 7, 1, 1],
       [1, 1, 2, 2, 5, 5]])

In [235]:
c = [{1,2,3,4},set(np.arange(4,9))]
np.array(b)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])