In [158]:
import pandas as pd
import numpy as np

In [5]:
lst1 = [n for n in np.arange(5)]
lst1

[0, 1, 2, 3, 4]

In [8]:
a = pd.Series(lst1)              # pandas series
a

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

In [13]:
a[2:]

2    2
3    3
4    4
5    5
dtype: int64

In [42]:
a.index

RangeIndex(start=0, stop=6, step=1)

In [21]:
a.values[:4]

array([0, 1, 2, 3])

In [168]:
b = pd.Series(lst1,index = ['a','b','c','d','e'])     # user-defined varb names
b

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [172]:
b['a']

0

In [173]:
b[['a']]

a    0
dtype: int64

In [174]:
b['a':'d']

a    0
b    1
c    2
d    3
dtype: int64

In [197]:
lst2 = {'x':True, 'y':True, "z":False}          # same logical
c = pd.Series(lst2)
c

x     True
y     True
z    False
dtype: bool

In [29]:
pd.Series(c,index = ('x','a','z','n'))             # pick some value if exists, otherwise NaN

x     True
a      NaN
z    False
n      NaN
dtype: object

In [34]:
c.name = 'T-F'
c.name

'T-F'

In [38]:
c.index.name = 'letter'
c

letter
x     True
y     True
z    False
Name: T-F, dtype: bool

In [41]:
c.drop('y')                     

letter
x     True
z    False
Name: T-F, dtype: bool

In [159]:
d = pd.DataFrame(lst1)           # special df
d

0
0  0
1  1
2  2
3  3
4  4

In [160]:
lst3 = (np.arange(6.).reshape((3,2)))
pd.DataFrame(lst3,columns=('even','odd'),index = list('abc'))


even  odd
a   0.0  1.0
b   2.0  3.0
c   4.0  5.0

In [161]:
lst3 = {'cars': ["BMW", "Volvo", "Ford"],
        'pass': [3, 7, 2],
        'import': [True, False, False]}
d = pd.DataFrame(lst3)
d

cars  pass  import
0    BMW     3    True
1  Volvo     7   False
2   Ford     2   False

In [140]:
pd.DataFrame(lst3,columns = ('pass','cars','nothing'))    
# adjust the position of cols and if does not exist then NaN, or we can use e.reindex(columns = ..., method = 'ffill')

pass   cars nothing
0     3    BMW     NaN
1     7  Volvo     NaN
2     2   Ford     NaN

In [166]:
d.index = (3,5,7)
d.drop('import',axis = 1)                # drop axis = column or axis = 1(recall above default is axis = 0(axis = index))

cars  pass
3    BMW     3
5  Volvo     7
7   Ford     2

In [166]:
d.values

array([['BMW', 3, True],
       ['Volvo', 7, False],
       ['Ford', 2, False]], dtype=object)

In [71]:
lst4 = {'Nevada': {2001: 2.4, 2002: 2.9},           # nested dic
        'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
lst4

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [206]:
e = pd.DataFrame(lst4)                             # inner key as row indices, outer key as col indices
e

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [74]:
e.index.name = 'year' 
e.columns.name = 'city'
e.name = 'pop'
e

city  Nevada  Ohio
year              
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

## work on col

In [184]:
e['Nevada']

year
2001    2.4
2002    2.9
2000    NaN
Name: Nevada, dtype: float64

In [530]:
e.Nevada

2001    2.4
2002    2.9
2000    NaN
Name: Nevada, dtype: float64

In [213]:
e.Nevada.values

array([2.4, 2.9, nan])

In [204]:
e.Nevada[2001]

2.4

In [76]:
e[['Nevada']]

city  Nevada
year        
2001     2.4
2002     2.9
2000     NaN

In [77]:
e.loc[:,'Ohio']

year
2001    1.7
2002    3.6
2000    1.5
Name: Ohio, dtype: float64

In [218]:
e.loc[:,['Ohio']]      # loc allows both index and varb name

Ohio
2001   1.7
2002   3.6
2000   1.5

In [82]:
e.iloc[:,[1]]        # only index works. we put [] inside index which resemble [[1]]

city  Ohio
year      
2001   1.7
2002   3.6
2000   1.5

In [222]:
e[['Ohio','Nevada']] # multiple col slice

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2000   1.5     NaN

In [223]:
e.iloc[:1,:2]

Nevada  Ohio
2001     2.4   1.7

## work on rows

In [159]:
e[1:]               # e[2000] does not work, so sad

city  Nevada  Ohio
year              
2002     2.9   3.6
2000     NaN   1.5

In [187]:
e.iloc[-1]

city
Nevada    NaN
Ohio      1.5
Name: 2000, dtype: float64

In [112]:
e.loc[[2000,2002]]  # multiple row slice

city  Nevada  Ohio
year              
2000     NaN   1.5
2002     2.9   3.6

In [113]:
# filter (can be a single value(0d); or series(1d); or df(2d))

In [116]:
e.loc[2000,'Ohio']

1.5

In [130]:
e.loc[2000,['Ohio']]

city
Ohio    1.5
Name: 2000, dtype: float64

In [129]:
e.loc[[2000],['Ohio']]

city  Ohio
year      
2000   1.5

## function mapping and application

In [227]:
df1 = pd.DataFrame(np.random.randint(1,20,(3,4)),columns = list('abcd'))
df1

a  b  c   d
0   9  4  6  16
1   1  5  6  19
2  15  6  7  11

In [232]:
f = lambda x: x.max() - x.min()
df1.apply(f,axis=1)

0    12
1    18
2     9
dtype: int64

In [237]:
f = lambda x: x ** 2 - x
df1.applymap(f)                    # only work in df and element-wise

a   b   c    d
0   72  12  30  240
1    0  20  30  342
2  210  30  42  110

In [ ]:
# df1['a'].map(function)          map only work for series

# sorting


In [275]:
df2 = pd.DataFrame(np.random.randint(0,20,(2,4)),index=['three', 'one'],columns=['d', 'a', 'b', 'c'])
df2

d  a   b   c
three  12  2   8   3
one     7  6  14  13

In [273]:
print(df2.sort_index(axis = 0))                    # sort row index
print(df2.sort_index(axis = 1, ascending=False))   # sort col index

        d   a   b  c
one     4  18  19  6
three  17   5  19  1
        d  c   b   a
three  17  1  19   5
one     4  6  19  18


In [283]:
print(df2.sort_values(by = 'a'))
print(df2.sort_values(by = list('ad')))
print(df2.sort_values(by = 'one',axis=1))

        d  a   b   c
three  12  2   8   3
one     7  6  14  13
        d  a   b   c
three  12  2   8   3
one     7  6  14  13
       a   d   c   b
three  2  12   3   8
one    6   7  13  14


# stats

In [284]:
df2.sum()

d    19
a     8
b    22
c    16
dtype: int64

In [287]:
df2.mean(axis=1,skipna=True)

three     6.25
one      10.00
dtype: float64

In [286]:
df2.describe()

d         a          b          c
count   2.000000  2.000000   2.000000   2.000000
mean    9.500000  4.000000  11.000000   8.000000
std     3.535534  2.828427   4.242641   7.071068
min     7.000000  2.000000   8.000000   3.000000
25%     8.250000  3.000000   9.500000   5.500000
50%     9.500000  4.000000  11.000000   8.000000
75%    10.750000  5.000000  12.500000  10.500000
max    12.000000  6.000000  14.000000  13.000000

# useful function


In [298]:
np.tile(np.array(np.arange(6)),3)

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

In [297]:
print(np.unique(np.tile(np.array(np.arange(6)),3)))
print(pd.unique(np.tile(np.array(np.arange(6)),3)))    # pd unique is faster

[0 1 2 3 4 5]
[0 1 2 3 4 5]


In [302]:
pd.value_counts(np.tile(np.array(np.arange(6)),3),sort=False)

0    3
1    3
2    3
3    3
4    3
5    3
dtype: int64

In [308]:
df3 = pd.Series(np.tile(np.array(np.arange(6)),3))
df3.isin(range(-1,3))

0      True
1      True
2      True
3     False
4     False
5     False
6      True
7      True
8      True
9     False
10    False
11    False
12     True
13     True
14     True
15    False
16    False
17    False
dtype: bool

# read file


In [332]:
d_f1 = pd.read_csv('data/practice.csv')
d_f1.head(n=11)

Animal Treatment  Glucose.0  Glucose.10
0   Control1   Control      1.599       1.599
1   Control2   Control      0.840       0.700
2   Control3   Control      0.220       0.100
3   Control4   Control      0.513       0.454
4   Control5   Control      0.592       0.513
5   Control6   Control      0.356       0.396
6   Control7   Control      0.595       0.595
7   Control8   Control      0.480       0.300
8       DCI1       DCI      0.705       0.604
9       DCI2       DCI        NaN       0.588
10      DCI3       DCI      0.689       0.709

In [338]:
d_f1 = pd.read_csv('data/practice.csv', header = None)                          # treat header as 1st row
print(d_f1.head(n=10))
print()

d_f1 = pd.read_csv('data/practice.csv', names = list('abcd'))                   # treat header as 1st row and new header is abcd
print(d_f1.head())
print()

d_f1 = pd.read_csv('data/practice.csv', skiprows = range(2), na_values=[.49])   # skip two rows and treat all .49 value to be NAN
print(d_f1)
print()
 
d_f1 = pd.read_csv('data/practice.csv', nrows=5)                                # onlt read 1st 5 row of file
print(d_f1)
print()


          0          1          2           3
0    Animal  Treatment  Glucose.0  Glucose.10
1  Control1    Control      1.599       1.599
2  Control2    Control       0.84         0.7
3  Control3    Control       0.22         0.1
4  Control4    Control      0.513       0.454
5  Control5    Control      0.592       0.513
6  Control6    Control      0.356       0.396
7  Control7    Control      0.595       0.595
8  Control8    Control       0.48         0.3
9      DCI1        DCI      0.705       0.604

          a          b          c           d
0    Animal  Treatment  Glucose.0  Glucose.10
1  Control1    Control      1.599       1.599
2  Control2    Control       0.84         0.7
3  Control3    Control       0.22         0.1
4  Control4    Control      0.513       0.454

    Control2  Control   0.84    0.7
0   Control3  Control  0.220  0.100
1   Control4  Control  0.513  0.454
2   Control5  Control  0.592  0.513
3   Control6  Control  0.356  0.396
4   Control7  Control  0.595  0.595


In [357]:
d_f2 = pd.read_table('data/file1',sep = '\n', header = None)
print(d_f2[[0]])
d_f2.to_csv('data/LoL.csv')   # write a csv

                                    0
0                              anivia
1                                 kat
2                            fizz zed
3        yasuo darius j4 annie ezreal
4                   vn mf ahri wukong
5  syndra lee xin cass cait amumu jax


In [538]:
d_f1.iloc[:,1].str.contains('Control')

0    True
1    True
2    True
3    True
4    True
Name: Treatment, dtype: bool

# handle the issue


## 1. deal with na value 

In [ ]:
# dropna() / fillna() / isna() / notnull()   etc

In [381]:
from numpy import nan as NA
d_f3 = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],[NA, NA, NA], [NA, 6.5, 3.]])
d_f3    

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [390]:
print(d_f3.dropna(axis=0))           # default is drop all row with NA
print()

print(d_f3.dropna(how = 'all'))      # drop all row with all NA
print()

print(d_f3.dropna(thresh = 1))       # thresh = num of element that the row must have, index 2 has 0 element so delete

     0    1    2
0  1.0  6.5  3.0

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0


In [395]:
print(d_f3.fillna(0))              # all na -> 0
print()

print(d_f3.fillna({1:0.1,2:.4}))   # fill value by col name
print()

print(d_f3.fillna(method = 'ffill', limit = 1, axis = 0))          # forward fill and only one NA will be filled 
print()

     0    1    2
0  1.0  6.5  3.0
1  1.0  0.0  0.0
2  0.0  0.0  0.0
3  0.0  6.5  3.0

     0    1    2
0  1.0  6.5  3.0
1  1.0  0.1  0.4
2  NaN  0.1  0.4
3  NaN  6.5  3.0

     0    1    2
0  1.0  6.5  3.0
1  1.0  6.5  3.0
2  1.0  NaN  NaN
3  NaN  6.5  3.0



## 2: remove duplicates

In [397]:
d_f4 = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],'k2': [1, 1, 2, 3, 3, 4, 4]})

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [399]:
d_f4.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [406]:
print(d_f4.drop_duplicates(['k1','k2'], keep = 'last'))         # 
print()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
6  two   4



## replace value and rename row/col

In [408]:
d_f4.k2.replace(2,np.nan)

0    1.0
1    1.0
2    NaN
3    3.0
4    3.0
5    4.0
6    4.0
Name: k2, dtype: float64

In [410]:
d_f4.k2.replace((2,3),(np.nan,300))

0      1.0
1      1.0
2      NaN
3    300.0
4    300.0
5      4.0
6      4.0
Name: k2, dtype: float64

In [417]:
d_f5 = pd.DataFrame(np.arange(12).reshape((3, 4)), 
                    index=['Ohio', 'Colorado', 'New york'], columns=['one', 'two', 'three', 'four'])
print(d_f5)
print()

print(d_f5.rename(index = str.title, columns = str.upper))                    # change catpital
print()

print(d_f5.rename(index={'Ohio': 'INDIANA'},columns={'three': 'peekaboo'}))   # change name of col

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New york    8    9     10    11

          ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

          one  two  peekaboo  four
INDIANA     0    1         2     3
Colorado    4    5         6     7
New york    8    9        10    11


## Discretization and Binning

In [429]:
age = [n for n in np.random.randint(1,80,10)]
bins = [n for n in np.sort(np.random.randint(25,100,6))]
bins[0] = 1
bins[-1] = 100
print(age)
print(bins)

[69, 41, 36, 67, 59, 30, 11, 31, 5, 32]
[1, 32, 33, 58, 64, 100]


In [450]:
cuts = pd.cut(age,bins, right = False)             # labels = ['','','','','',''] to replace the [1,32)
norm = pd.cut(np.random.randn(20),4,precision = 2) # an int means cut into n(here is 4) parts by its min and max element
qcut = pd.qcut(np.random.randn(20),4)              # cut into 4 parts with equally size
print(cuts, norm, qcut, pd.value_counts(qcut), sep = '\n\n')

[[64, 100), [33, 58), [33, 58), [64, 100), [58, 64), [1, 32), [1, 32), [1, 32), [1, 32), [32, 33)]
Categories (5, interval[int64, left]): [[1, 32) < [32, 33) < [33, 58) < [58, 64) < [64, 100)]

[(-1.21, -0.36], (0.49, 1.34], (-0.36, 0.49], (-2.06, -1.21], (-1.21, -0.36], ..., (0.49, 1.34], (-0.36, 0.49], (-1.21, -0.36], (0.49, 1.34], (0.49, 1.34]]
Length: 20
Categories (4, interval[float64, right]): [(-2.06, -1.21] < (-1.21, -0.36] < (-0.36, 0.49] < (0.49, 1.34]]

[(0.218, 2.738], (-0.38, -0.0983], (-1.18, -0.38], (-0.38, -0.0983], (0.218, 2.738], ..., (-0.0983, 0.218], (-1.18, -0.38], (-0.0983, 0.218], (-1.18, -0.38], (-1.18, -0.38]]
Length: 20
Categories (4, interval[float64, right]): [(-1.18, -0.38] < (-0.38, -0.0983] < (-0.0983, 0.218] < (0.218, 2.738]]

(-1.18, -0.38]      5
(-0.38, -0.0983]    5
(-0.0983, 0.218]    5
(0.218, 2.738]      5
dtype: int64


In [436]:
print(cuts.codes)         # return index of each elemen
print()
print(cuts.categories)    # summary
cuts.value_counts()       # frequnce count

[4 2 2 4 3 0 0 0 0 0]

IntervalIndex([(1, 32], (32, 33], (33, 58], (58, 64], (64, 100]], dtype='interval[int64, right]')


(1, 32]      5
(32, 33]     0
(33, 58]     2
(58, 64]     1
(64, 100]    2
dtype: int64

## Detecting and Filtering Outliers

In [470]:
rand1 = np.random.randn(2,5)
rand1

array([[-0.46922275,  0.557681  , -1.48732644, -0.20522916,  0.19551316],
       [ 0.33033053, -0.50662788,  0.67969091, -0.45644433, -0.10301929]])

In [474]:
print((np.abs(rand1) > 1).all(0))
print((np.abs(rand1) > 1).any(1))

[False False False False False]
[ True False]


array([ True, False])

In [476]:
d_f6 = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
perm = np.random.permutation(5)    # reorder 0-4
perm

array([1, 0, 3, 2, 4])

In [478]:
d_f6.take(perm,axis=0) # df with reordered index 

0   1   2   3
1   4   5   6   7
0   0   1   2   3
3  12  13  14  15
2   8   9  10  11
4  16  17  18  19

In [486]:
print(d_f6.sample(n=2,axis=1))
pd.Series(range(1,5)).sample(n=5,replace = True)

    2   1
0   2   1
1   6   5
2  10   9
3  14  13
4  18  17


2    3
3    4
3    4
0    1
3    4
dtype: int64

## Hierarchical Indexing

In [6]:
data = pd.Series(np.random.randn(9),index=[list('aaabbccdd'), [1, 2, 3, 1, 3, 1, 2, 3, 2]])
data    # hierarchical row index

a  1   -1.011509
   2   -0.342498
   3    0.986236
b  1   -0.088412
   3    1.039018
c  1    0.409636
   2   -0.299530
d  3   -0.117618
   2   -1.529661
dtype: float64

In [7]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 3),
            ('d', 2)],
           )

In [8]:
print(data['b'],data['b'][3], data[['b']],            # single outer index
      data[['b','d']], data.loc[:, 2],                # multiple index and inner index
      sep='\n\n')

1   -0.088412
3    1.039018
dtype: float64

1.0390175096885579

b  1   -0.088412
   3    1.039018
dtype: float64

b  1   -0.088412
   3    1.039018
d  3   -0.117618
   2   -1.529661
dtype: float64

a   -0.342498
c   -0.299530
d   -1.529661
dtype: float64


In [9]:
data.unstack()

1         2         3
a -1.011509 -0.342498  0.986236
b -0.088412       NaN  1.039018
c  0.409636 -0.299530       NaN
d       NaN -1.529661 -0.117618

In [175]:
print(pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]]), 
      pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)]), 
      pd.MultiIndex.from_product([[2013, 2014], [1, 2]],names=['year', 'visit']), sep = '\n\n')     # create MultiIndex

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

MultiIndex([(2013, 1),
            (2013, 2),
            (2014, 1),
            (2014, 2)],
           names=['year', 'visit'])


In [184]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),index=[list('aabb'), [1,2,1,2]],
                     columns=[['Ohio', 'Ohio', 'Colorado'],['Green', 'Red', 'Green']])
print(frame, frame.shape,sep='\n\n')                # hierarchical col and row index

     Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

(4, 3)


In [185]:
frame.index.names = ['key1', 'key2']
frame.columns.names = ['state', 'color']
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [186]:
print(frame['Ohio'], frame['Ohio']['Red'], frame.loc[:,('Ohio','Red')],
      frame.iloc[[1],:], sep = '\n\n') # extract element from multi-col

color      Green  Red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

key1  key2
a     1        1
      2        4
b     1        7
      2       10
Name: Red, dtype: int64

key1  key2
a     1        1
      2        4
b     1        7
      2       10
Name: (Ohio, Red), dtype: int64

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    2        3   4        5


In [187]:
frame.swaplevel('key1', 'key2')      # swap level

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [188]:
frame.swaplevel(0, 1).sort_index(level=0)    # 0 is key2 and 1 key1 here

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

In [189]:
print(frame.sum(level='key2'), frame.sum(level='color', axis = 1), sep = '\n\n')

state  Ohio     Colorado
color Green Red    Green
key2                    
1         6   8       10
2        12  14       16

color      Green  Red
key1 key2            
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10


/var/folders/ym/g88vgm455rxf69tz9h36ntjh0000gn/T/ipykernel_50531/3194264782.py:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  print(frame.sum(level='key2'), frame.sum(level='color', axis = 1), sep = '\n\n')


In [31]:
frame = pd.DataFrame({'a': range(7), 'b': range(7, 0, -1),
                      'c': ['one', 'one', 'one', 'two', 'two','two', 'two'],'d': [0, 1, 2, 0, 1, 2, 3]})

frame2 = frame.set_index(list('cd'),drop = True)  # drop = T means drop c,d from df

frame3 = frame2.reset_index()                     # unstack multi_row

print(frame, frame2, frame3, sep = '\n\n') 

   a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

       a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

     c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1


# merge and combine df

## many-to-one

In [43]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'n1' : range(7),'keys': list('bbacaab')})
df2 = df2 = pd.DataFrame({'key': ['a', 'b', 'd'], 'n2': range(3)})
print(df1, df2, sep='\n\n')                

  key  n1 keys
0   b   0    b
1   b   1    b
2   a   2    a
3   c   3    c
4   a   4    a
5   a   5    a
6   b   6    b

  key  n2
0   a   0
1   b   1
2   d   2


In [46]:
print(pd.merge(df1,df2), pd.merge(df1,df2,on='key'),      # specify the col that need to be merged(must be exist both)
      pd.merge(df1,df2,how = 'outer'),                    # inner is intersection(default), outer is union, left/right
      pd.merge(df1,df2,left_on = 'key', right_on = 'key') # specify seprately if col-names are diff in two df
      , sep='\n\n')         

  key  n1 keys  n2
0   b   0    b   1
1   b   1    b   1
2   b   6    b   1
3   a   2    a   0
4   a   4    a   0
5   a   5    a   0

  key  n1 keys  n2
0   b   0    b   1
1   b   1    b   1
2   b   6    b   1
3   a   2    a   0
4   a   4    a   0
5   a   5    a   0

  key   n1 keys   n2
0   b  0.0    b  1.0
1   b  1.0    b  1.0
2   b  6.0    b  1.0
3   a  2.0    a  0.0
4   a  4.0    a  0.0
5   a  5.0    a  0.0
6   c  3.0    c  NaN
7   d  NaN  NaN  2.0

  key  n1 keys  n2
0   b   0    b   1
1   b   1    b   1
2   b   6    b   1
3   a   2    a   0
4   a   4    a   0
5   a   5    a   0


## Many-to-many

In [64]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'], 'data1': range(6), 'key1':list('abcdab')})
df2 = pd.DataFrame({'key': ['a', 'b', 'a', 'b', 'd'], 'data2': range(5), 'key1':list('dcbaa')})
print(df1, df2, sep='\n\n')

  key  data1 key1
0   b      0    a
1   b      1    b
2   a      2    c
3   c      3    d
4   a      4    a
5   b      5    b

  key  data2 key1
0   a      0    d
1   b      1    c
2   a      2    b
3   b      3    a
4   d      4    a


In [56]:
pd.merge(df1.iloc[:,:2],df2.iloc[:,:2],how='inner',on='key') 
# we can see that 3b in df1 and 2b in df2, so 2*3=6, it assembles recycling rule

key  data1  data2
0   b      0      1
1   b      0      3
2   b      1      1
3   b      1      3
4   b      5      1
5   b      5      3
6   a      2      0
7   a      2      2
8   a      4      0
9   a      4      2

In [57]:
pd.merge(df1.iloc[:,:2],df2.iloc[:,:2], how='left',on='key')

key  data1  data2
0    b      0    1.0
1    b      0    3.0
2    b      1    1.0
3    b      1    3.0
4    a      2    0.0
5    a      2    2.0
6    c      3    NaN
7    a      4    0.0
8    a      4    2.0
9    b      5    1.0
10   b      5    3.0

In [63]:
new = pd.merge(df1, df2, on = ['key','key1'], how = 'outer')
print(new, new.replace(np.nan,-1), new[['key','key1','data1','data2']], sep='\n\n')

  key  data1 key1  data2
0   b    0.0    a    3.0
1   b    1.0    b    NaN
2   b    5.0    b    NaN
3   a    2.0    c    NaN
4   c    3.0    d    NaN
5   a    4.0    a    NaN
6   a    NaN    d    0.0
7   b    NaN    c    1.0
8   a    NaN    b    2.0
9   d    NaN    a    4.0

  key  data1 key1  data2
0   b    0.0    a    3.0
1   b    1.0    b   -1.0
2   b    5.0    b   -1.0
3   a    2.0    c   -1.0
4   c    3.0    d   -1.0
5   a    4.0    a   -1.0
6   a   -1.0    d    0.0
7   b   -1.0    c    1.0
8   a   -1.0    b    2.0
9   d   -1.0    a    4.0

  key key1  data1  data2
0   b    a    0.0    3.0
1   b    b    1.0    NaN
2   b    b    5.0    NaN
3   a    c    2.0    NaN
4   c    d    3.0    NaN
5   a    a    4.0    NaN
6   a    d    NaN    0.0
7   b    c    NaN    1.0
8   a    b    NaN    2.0
9   d    a    NaN    4.0


In [190]:
pd.merge(df1, df2.set_index('key1'),left_on='key',right_index=True,how='outer')  # specify col and index 

key key_x  data1 key1 key_y  data2
0.0   b     b    0.0    a     a      2
1.0   b     b    1.0    b     a      2
5.0   b     b    5.0    b     a      2
2.0   a     a    2.0    c     b      3
2.0   a     a    2.0    c     d      4
4.0   a     a    4.0    a     b      3
4.0   a     a    4.0    a     d      4
3.0   c     c    3.0    d     b      1
NaN   d   NaN    NaN  NaN     a      0

In [74]:
df1.set_index('key')[['data1']].join(df2.set_index('key')[['data2']])    # we can use join when merge df by indexes

data1  data2
key              
a        2    0.0
a        2    2.0
a        4    0.0
a        4    2.0
b        0    1.0
b        0    3.0
b        1    1.0
b        1    3.0
b        5    1.0
b        5    3.0
c        3    NaN

# Concatenating Along an Axis

In [77]:
arr = np.arange(12).reshape((3, 4))
print(np.concatenate([arr,arr],axis=0),np.concatenate([arr,arr],axis=1),sep='\n\n') # numpy concatenate

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]


In [92]:
s1 = pd.Series([0, 1], index=['a', 'b'])
s2 = pd.Series([2, 3, 4], index=['c', 'a', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])

print(pd.concat([s1,s2,s3]), pd.concat([s1,s2,s3],axis=1),                    # pandas concatenate
      pd.concat([s1,s2],join='inner',axis=1), 
      pd.concat([s1,s2,s3], axis=0, keys = ['ad','ap','po']),                 # get outer index names if inner existed
      pd.concat([s1,s2], axis=1,keys = ['mid','top']),sep='\n\n')             # replace default names

a    0
b    1
c    2
a    3
e    4
f    5
g    6
dtype: int64

     0    1    2
a  0.0  3.0  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

   0  1
a  0  3

ad  a    0
    b    1
ap  c    2
    a    3
    e    4
po  f    5
    g    6
dtype: int64

   mid  top
a  0.0  3.0
b  1.0  NaN
c  NaN  2.0
e  NaN  4.0


## GroupBy Mechanics

In [93]:
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],'key2' : ['one', 'two', 'one', 'two', 'one'],
                   'data1' : np.random.randn(5),'data2' : np.random.randn(5)})
df

key1 key2     data1     data2
0    a  one  0.916814  0.243839
1    a  two  2.034608  1.145257
2    b  one -0.462939 -0.366811
3    b  two -1.260521  0.694885
4    a  one -0.132300 -1.827080

In [103]:
df.data1.groupby(df.key1).mean()

key1
a    0.939707
b   -0.861730
Name: data1, dtype: float64

In [107]:
print(df.groupby(['key1','key2']).size(), df['data1'].groupby([df['key1'], df['key2']]).mean(), sep = '\n\n')
# 1st snippet we pass whole df but 2nd we pass df['data1'], so have to specify which col we goona group

key1  key2
a     one     2
      two     1
b     one     1
      two     1
dtype: int64

key1  key2
a     one     0.392257
      two     2.034608
b     one    -0.462939
      two    -1.260521
Name: data1, dtype: float64


In [113]:
for name, group in df.groupby('key1'):
    print(name)
    print(group)

a

  key1 key2     data1     data2
0    a  one  0.916814  0.243839
1    a  two  2.034608  1.145257
4    a  one -0.132300 -1.827080
b

  key1 key2     data1     data2
2    b  one -0.462939 -0.366811
3    b  two -1.260521  0.694885


In [115]:
for (k1,k2), group in df.groupby(['key1','key2']):
    print((k1,k2))
    print(group)

('a', 'one')
  key1 key2     data1     data2
0    a  one  0.916814  0.243839
4    a  one -0.132300 -1.827080
('a', 'two')
  key1 key2     data1     data2
1    a  two  2.034608  1.145257
('b', 'one')
  key1 key2     data1     data2
2    b  one -0.462939 -0.366811
('b', 'two')
  key1 key2     data1     data2
3    b  two -1.260521  0.694885


In [141]:
print(df.groupby('key1'), list(df.groupby('key1')), 
      dict(list(df.groupby('key1'))), df.groupby('key1').describe(), sep='\n\n')


[('a',   key1 key2     data1     data2
0    a  one  0.916814  0.243839
1    a  two  2.034608  1.145257
4    a  one -0.132300 -1.827080), ('b',   key1 key2     data1     data2
2    b  one -0.462939 -0.366811
3    b  two -1.260521  0.694885)]

{'a':   key1 key2     data1     data2
0    a  one  0.916814  0.243839
1    a  two  2.034608  1.145257
4    a  one -0.132300 -1.827080, 'b':   key1 key2     data1     data2
2    b  one -0.462939 -0.366811
3    b  two -1.260521  0.694885}

     data1                                                              \
     count      mean       std       min       25%       50%       75%   
key1                                                                     
a      3.0  0.939707  1.083635 -0.132300  0.392257  0.916814  1.475711   
b      2.0 -0.861730  0.563976 -1.260521 -1.061126 -0.861730 -0.662334   

               data2                                                    \
           max count      mean       std       min       25%       50%   


In [123]:
df.groupby('key1')['data1'].mean()

key1
a    0.939707
b   -0.861730
Name: data1, dtype: float64

In [140]:
people = pd.DataFrame(np.random.randn(5, 5), columns=['a', 'b', 'c', 'd', 'e'],
                      index=['Joe', 'Steve', 'Wes', 'Jim', 'Travis'])

mapping = {'a': 'red', 'b': 'red', 'c': 'blue', 'd': 'blue', 'e': 'red', 'f' : 'orange'}

people

a         b         c         d         e
Joe     0.730376 -1.218287 -1.038941  1.484258  0.528385
Steve  -0.253859 -2.107957 -0.592869  1.007135 -1.160972
Wes     0.055652  0.344349 -0.039094 -1.228394  0.511263
Jim    -1.977797  0.731435  0.792647  0.895742 -0.338822
Travis  0.697977 -0.977666  1.015928  1.015612  0.872401

In [135]:
people.iloc[[2],[1,2]] = np.nan
people.groupby(mapping, axis=1).sum()

blue       red
Joe    -0.429754  1.394450
Steve  -0.845104 -1.951585
Wes    -1.741770 -0.087229
Jim    -0.423040 -0.561851
Travis  0.316052  1.181225

In [138]:
list(people.groupby(len))   # len of index 

[(3,
              a         b         c         d         e
  Joe -0.474300  1.266155  0.529213 -0.958967  0.602595
  Wes -1.278169       NaN       NaN -1.741770  1.190940
  Jim  0.838174 -1.204627  0.985070 -1.408110 -0.195398),
 (5,
                a        b         c         d         e
  Steve -0.085376 -1.88513  1.481543 -2.326646  0.018921),
 (6,
                a         b         c         d         e
  Travis  0.79725 -0.338759 -1.579597  1.895649  0.722735)]

# Data Aggregation

In [145]:
tips = pd.read_csv('data/tips.csv')
tips['tip_pct'] = tips['tip'] / tips['total_bill']
tips.head()

total_bill   tip     sex smoker  day    time  size   tip_pct
0       16.99  1.01  Female     No  Sun  Dinner     2  0.059447
1       10.34  1.66    Male     No  Sun  Dinner     3  0.160542
2       21.01  3.50    Male     No  Sun  Dinner     3  0.166587
3       23.68  3.31    Male     No  Sun  Dinner     2  0.139780
4       24.59  3.61  Female     No  Sun  Dinner     4  0.146808

In [149]:
tips.groupby(['day', 'smoker']).tip_pct.agg(['mean','count','std'])

mean  count       std
day  smoker                           
Fri  No      0.151650      4  0.028123
     Yes     0.174783     15  0.051293
Sat  No      0.158048     45  0.039767
     Yes     0.147906     42  0.061375
Sun  No      0.160113     57  0.042347
     Yes     0.187250     19  0.154134
Thur No      0.160298     45  0.038774
     Yes     0.163863     17  0.039389

In [153]:
tips.groupby(['day', 'smoker']).tip_pct.agg([('ave','mean'),'count',('std',np.std)])   # or use tuple for its names

ave  count       std
day  smoker                           
Fri  No      0.151650      4  0.028123
     Yes     0.174783     15  0.051293
Sat  No      0.158048     45  0.039767
     Yes     0.147906     42  0.061375
Sun  No      0.160113     57  0.042347
     Yes     0.187250     19  0.154134
Thur No      0.160298     45  0.038774
     Yes     0.163863     17  0.039389

In [210]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
titanic = titanic.rename(columns = {'who':'whos'})
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

    whos  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [199]:
print(titanic.groupby(['sex','class'])['survived'].mean().unstack(),                     # or agg('mean')
      titanic.pivot_table('survived', index = 'sex', columns = 'class'), sep = '\n\n') 

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447


In [214]:
print(titanic.pivot_table(values = 'survived', index = ['sex','whos'], columns = ['class','alive'], fill_value = -1),
     titanic.pivot_table(index='sex', columns='class', aggfunc={'survived':sum, 'fare':'mean'}), sep = '\n\n')

class        First     Second     Third    
alive           no yes     no yes    no yes
sex    whos                                
female child     0   1     -1   1     0   1
       woman     0   1      0   1     0   1
male   child    -1   1     -1   1     0   1
       man       0   1      0   1     0   1

              fare                       survived             
class        First     Second      Third    First Second Third
sex                                                           
female  106.125798  21.970121  16.118810       91     70    72
male     67.226127  19.741782  12.661633       45     17    47


## string manipulation

In [219]:
titanic.columns
strs = titanic.embark_town
strs

0      Southampton
1        Cherbourg
2      Southampton
3      Southampton
4      Southampton
          ...     
886    Southampton
887    Southampton
888    Southampton
889      Cherbourg
890     Queenstown
Name: embark_town, Length: 891, dtype: object

In [233]:
print(strs.str.lower(),strs.str.upper(), strs.str.len(),                                   # convert to lower/upper and count letters of each
     strs.str.startswith('S'), strs.str.contains('s'), strs.str.extract('([SC]+)'), sep='\n\n\n') # regular expression can be applied to here

0      southampton
1        cherbourg
2      southampton
3      southampton
4      southampton
          ...     
886    southampton
887    southampton
888    southampton
889      cherbourg
890     queenstown
Name: embark_town, Length: 891, dtype: object


0      SOUTHAMPTON
1        CHERBOURG
2      SOUTHAMPTON
3      SOUTHAMPTON
4      SOUTHAMPTON
          ...     
886    SOUTHAMPTON
887    SOUTHAMPTON
888    SOUTHAMPTON
889      CHERBOURG
890     QUEENSTOWN
Name: embark_town, Length: 891, dtype: object


0      11.0
1       9.0
2      11.0
3      11.0
4      11.0
       ... 
886    11.0
887    11.0
888    11.0
889     9.0
890    10.0
Name: embark_town, Length: 891, dtype: float64


0       True
1      False
2       True
3       True
4       True
       ...  
886     True
887     True
888     True
889    False
890    False
Name: embark_town, Length: 891, dtype: object


0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888    Fal